Fixing small plotting and settings issues
floracharbo/MARL_local_electricity pull request #9
Opened 2023-01-27 14:05 UTC by julie-vienne

This PR will take care of small issues that do not add or change features.

2023-01-27 14:50 UTC, floracharbo requested changes

2023-01-27 14:50 UTC, floracharbo commented on src/post_analysis/plotting/plot_episode_results.py
> +            ax2.set_ylim([0, 1.1 * max(import_export_costs)])
is this not done automatically if you remove `set_ylim`?

2023-01-27 14:50 UTC, floracharbo commented on src/post_analysis/plotting/plot_moving_average_rewards.py
> +    #plt.gca().set_yticks(np.arange(-0.15, 0.2, 0.05))
remove if not used? or would you like to keep it to sometimes use it?

2023-01-27 17:03 UTC, julie-vienne commented
@floracharbo I've made some changes to debug running only `manage_agg_power`. Let me know what you think and if we can merge with main as I need it to run some experiments.

2023-01-27 17:25 UTC, floracharbo requested changes

2023-01-27 17:25 UTC, floracharbo commented on src/simulations/local_elec.py
> +        if self.prm['grd']['manage_voltage'] or self.prm['grd']['manage_agg_power']:
no let's not create the whole network object just to manage agg power. This is unnecessary.

2023-01-27 17:25 UTC, floracharbo commented on src/simulations/local_elec.py
> +                    else None
yes! I noticed this problem also. My bad I caused this problem when I debugged the comparison between optimisation and pandapower. I had fixed this in the main branch in parallel.

2023-01-27 17:25 UTC, floracharbo commented on src/simulations/optimisation.py
> +            res['hourly_line_losses'] = np.zeros(self.N)
yes thanks for this. Sorry to have caused this issue. I think we duplicate the work as I had fixed this in the main branch.

2023-01-27 17:25 UTC, floracharbo commented on main.py
>  }
maybe it is best if we don't commit the main files if only the settings change? then it disturbs the settings of whatever experiment we were running. I will create an issue to have the settings be a separate file that we add on .gitignore.

2023-01-27 17:25 UTC, floracharbo commented on src/simulations/optimisation.py
> +            res['hourly_line_losses'] = np.zeros(self.N)
could you please merge the main branch with this branch to harmonise before merging else there will be conflicts as we have solved the same problem and edited the same lines.

2023-02-01 16:21 UTC, julie-vienne commented
@floracharbo this PR does not fix all a lot of problems but can still be merge easily. I believe it is now ready to be merged.

2023-02-01 18:06 UTC, floracharbo commented
should I close this @julie-vienne ?

2023-02-01 18:28 UTC, floracharbo commented
> @floracharbo this PR does not fix all a lot of problems but can still be merge easily. I believe it is now ready to be merged.

everything in this PR is also in https://github.com/floracharbo/MARL_local_electricity/pull/13. I think if we merge them both we will end up having conflicts because editing twice the same lines. We might as well just do the "computational burden" PR.

2023-02-02 08:11 UTC, julie-vienne commented
Close, see #13

2023-02-02 08:11 UTC, closed without merging